language: php
env: VFS_SQL_PDO_PGSQL_TEST_CONFIG='{"vfs":{"sql":{"pdo_pgsql":{"adapter":"pdo_pgsql","username":"postgres","password":"","dbname":"test","charset":"utf-8"}}}}' VFS_SQL_PDO_MYSQL_TEST_CONFIG='{"vfs":{"sql":{"pdo_mysql":{"adapter":"pdo_mysql","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}' VFS_SQL_MYSQL_TEST_CONFIG='{"vfs":{"sql":{"mysql":{"adapter":"mysql","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}' VFS_SQL_MYSQLI_TEST_CONFIG='{"vfs":{"sql":{"mysqli":{"adapter":"mysqli","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}'
#services:
#  - memcache
before_install:
  - sudo locale-gen de_DE.UTF-8 tr_TR.UTF-8
  - sudo apt-get install -qq libwbxml2-utils
before_script:
  - yes | pecl install memcache
  - pear install channel://pear.horde.org/Horde_Role
  - pear install channel://pear.phpunit.de/PHPUnit_Story
  - ./framework/bin/pear_batch_install
#  - mysql -e 'create database test;'
  - psql -c 'create database test;' -U postgres
script: ./framework/bin/test_framework --verbose
