sudo: false
notifications:
  irc: "chat.freenode.net#horde"
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - php:
      - nightly
      - 7.1
      - 7.0
services:
  - memcached
  - mongodb
  - mysql
  - postgresql
  - redis-server
addons:
  apt:
    packages:
      - aspell
      - aspell-en
      - cvs
      - cvsps
      - language-pack-en
      - language-pack-cs
      - language-pack-de
      - language-pack-tr
      - libimage-exiftool-perl
      - libwbxml2-utils
      - rcs
before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
before_script:
  - export ACTIVESYNC_MONGO_TEST_CONFIG='{"activesync":{"mongo":{"hostspec":"localhost"}}}';
    export ACTIVESYNC_SQL_MYSQL_TEST_CONFIG='{"activesync":{"sql":{"mysql":{"adapter":"mysql","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export ACTIVESYNC_SQL_MYSQLI_TEST_CONFIG='{"activesync":{"sql":{"mysqli":{"adapter":"mysqli","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export ACTIVESYNC_SQL_PDO_MYSQL_TEST_CONFIG='{"activesync":{"sql":{"pdo_mysql":{"adapter":"pdo_mysql","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export ALARM_SQL_MYSQL_TEST_CONFIG='{"alarm":{"sql":{"mysql":{"adapter":"mysql","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export ALARM_SQL_MYSQLI_TEST_CONFIG='{"alarm":{"sql":{"mysqli":{"adapter":"mysqli","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export ALARM_SQL_PDO_MYSQL_TEST_CONFIG='{"alarm":{"sql":{"pdo_mysql":{"adapter":"pdo_mysql","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export ALARM_SQL_PDO_PGSQL_TEST_CONFIG='{"alarm":{"sql":{"pdo_pgsql":{"adapter":"pdo_pgsql","username":"postgres","password":"","dbname":"test","charset":"utf-8"}}}}';
    export CACHE_MEMCACHE_TEST_CONFIG='{"cache":{"memcache":{"hostspec":["localhost"],"port":[11211]}}}';
    export CACHE_MONGO_TEST_CONFIG='{"cache":{"mongo":{"hostspec":"mongodb://localhost"}}}';
    export CACHE_SQL_MYSQL_TEST_CONFIG='{"cache":{"sql":{"mysql":{"adapter":"mysql","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export CACHE_SQL_MYSQLI_TEST_CONFIG='{"cache":{"sql":{"mysqli":{"adapter":"mysqli","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export CACHE_SQL_PDO_MYSQL_TEST_CONFIG='{"cache":{"sql":{"pdo_mysql":{"adapter":"pdo_mysql","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export CACHE_SQL_PDO_PGSQL_TEST_CONFIG='{"cache":{"sql":{"pdo_pgsql":{"adapter":"pdo_pgsql","username":"postgres","password":"","dbname":"test","charset":"utf-8"}}}}';
    export CRYPT_TEST_CONFIG='{"crypt":{"keyserver":false}}';
    export CRYPTPGP_TEST_CONFIG='{"gnupg":"/usr/bin/gnupg","gnupg2":"/usr/bin/gnupg2"}';
    export DB_ADAPTER_MYSQL_TEST_CONFIG='{"db":{"adapter":{"mysql":{"test":{"host":"localhost","username":"root","password":"","dbname":"test"}}}}}';
    export DB_ADAPTER_MYSQLI_TEST_CONFIG='{"db":{"adapter":{"mysqli":{"test":{"host":"localhost","username":"root","password":"","dbname":"test"}}}}}';
    export DB_ADAPTER_PDO_MYSQL_TEST_CONFIG='{"db":{"adapter":{"pdo":{"mysql":{"test":{"host":"localhost","username":"root","password":"","dbname":"test"}}}}}}';
    export DB_ADAPTER_PDO_PGSQL_TEST_CONFIG='{"db":{"adapter":{"pdo":{"pgsql":{"test":{"username":"postgres","password":"","dbname":"test"}}}}}}';
    export GROUP_SQL_MYSQL_TEST_CONFIG='{"group":{"sql":{"mysql":{"adapter":"mysql","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export GROUP_SQL_MYSQLI_TEST_CONFIG='{"group":{"sql":{"mysqli":{"adapter":"mysqli","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export GROUP_SQL_PDO_MYSQL_TEST_CONFIG='{"group":{"sql":{"pdo_mysql":{"adapter":"pdo_mysql","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export GROUP_SQL_PDO_PGSQL_TEST_CONFIG='{"group":{"sql":{"pdo_pgsql":{"adapter":"pdo_pgsql","username":"postgres","password":"","dbname":"test","charset":"utf-8"}}}}';
    export HASHTABLE_MEMCACHE_TEST_CONFIG='{"hashtable":{"memcache":{"hostspec":["localhost"],"port":[11211]}}}';
    export HASHTABLE_PREDIS_TEST_CONFIG='{"hashtable":{"predis":{"hostspec":["localhost"],"scheme":"tcp","database":0}}}';
    export HISTORY_MONGO_TEST_CONFIG='{"history":{"mongo":"mongodb://localhost"}}';
    export HISTORY_SQL_MYSQL_TEST_CONFIG='{"history":{"sql":{"mysql":{"adapter":"mysql","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export HISTORY_SQL_MYSQLI_TEST_CONFIG='{"history":{"sql":{"mysqli":{"adapter":"mysqli","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export HISTORY_SQL_PDO_MYSQL_TEST_CONFIG='{"history":{"sql":{"pdo_mysql":{"adapter":"pdo_mysql","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export HISTORY_SQL_PDO_PGSQL_TEST_CONFIG='{"history":{"sql":{"pdo_pgsql":{"adapter":"pdo_pgsql","username":"postgres","password":"","dbname":"test","charset":"utf-8"}}}}';
    export HTTP_TEST_CONFIG='{"http":{"server":"www.google.com"}}';
    export IMAGE_EXIF_TEST_CONFIG='{"image":{"exiftool":"/usr/bin/exiftool"}}';
    export IMAPCLIENT_TEST_CONFIG='{"mongo":"localhost"}';
    export MAILAUTOCONFIG_TEST_CONFIG='{"mail_autoconfig":{"nonauth_emails":["test@gmail.com","test@gmx.net"],"nonauth_emails_bad":["test@example.com"],"domains":[[["gmail.com"]],[["test.mail.gmail.com","mail.gmail.com","gmail.com"]]]}}';
    export LOCK_MONGO_TEST_CONFIG='{"lock":{"mongo":"localhost"}}';
    export PEAR_TEST_CONFIG='{"pear":{"config":"/etc/pear/pear.conf","server":"pear.horde.org"}}';
    export PREFS_SQL_MYSQL_TEST_CONFIG='{"prefs":{"sql":{"mysql":{"adapter":"mysql","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export PREFS_SQL_MYSQLI_TEST_CONFIG='{"prefs":{"sql":{"mysqli":{"adapter":"mysqli","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export PREFS_SQL_PDO_MYSQL_TEST_CONFIG='{"prefs":{"sql":{"pdo_mysql":{"adapter":"pdo_mysql","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export PREFS_SQL_PDO_PGSQL_TEST_CONFIG='{"prefs":{"sql":{"pdo_pgsql":{"adapter":"pdo_pgsql","username":"postgres","password":"","dbname":"test","charset":"utf-8"}}}}';
    export SERVICE_GRAVATAR_TEST_CONFIG='{"service":{"gravatar":{"server":"http://www.gravatar.com"}}}';
    export SESSIONHANDLER_MEMCACHE_TEST_CONFIG='{"sessionhandler":{"memcache":{"hostspec":["localhost"],"port":[11211]}}}';
    export SESSIONHANDLER_MONGO_TEST_CONFIG='{"sessionhandler":{"mongo":"mongodb://localhost"}}';
    export SESSIONHANDLER_SQL_MYSQL_TEST_CONFIG='{"sessionhandler":{"sql":{"mysql":{"adapter":"mysql","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export SESSIONHANDLER_SQL_MYSQLI_TEST_CONFIG='{"sessionhandler":{"sql":{"mysqli":{"adapter":"mysqli","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export SESSIONHANDLER_SQL_PDO_MYSQL_TEST_CONFIG='{"sessionhandler":{"sql":{"pdo_mysql":{"adapter":"pdo_mysql","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export SESSIONHANDLER_SQL_PDO_PGSQL_TEST_CONFIG='{"sessionhandler":{"sql":{"pdo_pgsql":{"adapter":"pdo_pgsql","username":"postgres","password":"","dbname":"test","charset":"utf-8"}}}}';
    export SHARE_SQL_MYSQL_TEST_CONFIG='{"share":{"sql":{"mysql":{"adapter":"mysql","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export SHARE_SQL_MYSQLI_TEST_CONFIG='{"share":{"sql":{"mysqli":{"adapter":"mysqli","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export SHARE_SQL_PDO_MYSQL_TEST_CONFIG='{"share":{"sql":{"pdo_mysql":{"adapter":"pdo_mysql","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export SHARE_SQL_PDO_PGSQL_TEST_CONFIG='{"share":{"sql":{"pdo_pgsql":{"adapter":"pdo_pgsql","username":"postgres","password":"","dbname":"test","charset":"utf-8"}}}}';
    export TOKEN_MONGO_TEST_CONFIG='{"token":{"mongo":"localhost"}}';
    export VCS_TEST_CONFIG='{"paths":{"ci":"\/usr\/bin\/ci","co":"\/usr\/bin\/co","rcs":"\/usr\/bin\/rcs","rcsdiff":"\/usr\/bin\/rcsdiff","rlog":"\/usr\/bin\/rlog","cvs":"\/usr\/bin\/cvs","cvsps":"\/usr\/bin\/cvsps","cvsps_home":"\/tmp","svn":"\/usr\/bin\/svn","diff":"\/usr\/bin\/diff","git":"\/usr\/bin\/git"}}';
    export VFS_MONGO_TEST_CONFIG='{"vfs":{"mongo":{"hostspec":"localhost"}}}';
    export VFS_SQL_MYSQL_TEST_CONFIG='{"vfs":{"sql":{"mysql":{"adapter":"mysql","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export VFS_SQL_MYSQLI_TEST_CONFIG='{"vfs":{"sql":{"mysqli":{"adapter":"mysqli","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export VFS_SQL_PDO_MYSQL_TEST_CONFIG='{"vfs":{"sql":{"pdo_mysql":{"adapter":"pdo_mysql","host":"localhost","username":"root","password":"","dbname":"test","charset":"utf-8"}}}}';
    export VFS_SQL_PDO_PGSQL_TEST_CONFIG='{"vfs":{"sql":{"pdo_pgsql":{"adapter":"pdo_pgsql","username":"postgres","password":"","dbname":"test","charset":"utf-8"}}}}';
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ] || [ $(echo "$TRAVIS_PHP_VERSION 7.0" | tr " " "\n" | sort -V | head -n1) = "7.0" ];
    then
        phpenv config-add .travis.php7.ini;
        yes "" | pecl install channel://pecl.php.net/pecl_http channel://pecl.php.net/msgpack-beta;
    else
        phpenv config-add .travis.ini;
        yes "" | pecl install channel://pecl.php.net/igbinary channel://pecl.php.net/raphf-1.1.2 channel://pecl.php.net/propro-1.0.2 channel://pecl.php.net/pecl_http-2.5.6 channel://pecl.php.net/msgpack-0.5.7;
    fi
  - phpenv config-rm xdebug.ini || echo "XDebug not enabled"
  - yes no | pecl install channel://pecl.php.net/lzf
  - pear install channel://pear.php.net/Math_BigInteger
  - pear install channel://pear.php.net/Net_DNS2
  - pear install channel://pear.horde.org/Horde_Role
  - pear install channel://pear.nrk.io/Predis
  - ./framework/bin/pear_batch_install
  - psql -c 'create database test;' -U postgres
script:
  - ./framework/bin/test_framework
