language: php
before_script:
  - pear install channel://pear.horde.org/Horde_Role
  - pear install channel://pear.phpunit.de/PHPUnit_Story
  - ./framework/bin/pear_batch_install
script: ./framework/bin/test_framework
notifications:
  email: jan@horde.org
